name: Manual Deploy to DO

on:
  workflow_dispatch:
    inputs:
      image_digest:
        description: 'Image digest to deploy'
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to App Platform
        uses: digitalocean/app_action/deploy@cc55bc9b848d25f9c1c9f831cf843fbab3fbfb15 # v2
        env:
          IMAGE_DIGEST: ${{ inputs.image_digest }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
